"""
Django settings for kantineApp project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from os import path, environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ.get(
    "DJANGO_KEY", 'django-insecure-9@e#u@ku@*$_y@1o80$a0wjohz49t@!q&wotmcfsnw(l+v$!8*')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = environ.get("DEBUG", False)


# Application definition

INSTALLED_APPS = [
    'kasseBE.apps.KassebeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]


# If this is used then `CORS_ALLOWED_ORIGINS` will not have any effect
# CORS_ALLOW_ALL_ORIGINS = not environ.get("FRONTEND_DOMAIN", None)
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SECURE = False    # erlaubt HTTP

ALLOWED_HOSTS = ["localhost", "kantinekasse", "kantinekasse.impulsreha.local",
                 "127.0.0.1", "elbkantine.impuls-reha.de"]

SESSION_SAVE_EVERY_REQUEST = True
# SESSION_COOKIE_SAMESITE = 'None'


# enable when we get https
# CSRF_COOKIE_SECURE = False

CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS = [
    "http://"+o for o in ALLOWED_HOSTS] + ["https://"+o for o in ALLOWED_HOSTS]
print(CORS_ALLOWED_ORIGINS)
print()
print(CSRF_TRUSTED_ORIGINS)
print()

ROOT_URLCONF = 'kantineApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kantineApp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': "django.db.backends."+environ.get("DB_ENGINE", 'sqlite3'),
        'NAME': environ.get("DB_NAME", 'kursplan.sqlite3'),
        'USER': environ.get("DB_USER", 'root'),
        'PASSWORD': environ.get("DB_PASSWORD", 'root'),
        'HOST': environ.get("DB_ADDR", '127.0.0.1'),
        'PORT': environ.get("DB_PORT", '3306'),
        'TEST': {
            # 'MIRROR': 'default',
            'NAME': 'mytestdatabase',
        }
    }
}

# print(DATABASES)
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'CET'

USE_I18N = True


LANGUAGES = [
    ['en', 'English'],
    ['de', 'Deutsch']
]


LOCALE_PATHS = [
    path.join(BASE_DIR, 'locales')
]

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_ROOT = path.join(BASE_DIR, 'static')
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    # BASE_DIR / "static",
    BASE_DIR / "frontend"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
